name: chord
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  google_sign_in: ^6.2.1
  file_picker: ^8.0.0+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  sqflite: ^2.3.0
  permission_handler: ^11.3.1
  http: ^1.2.2
  call_log: ^6.0.1
  crypto: ^3.0.3
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
